/*********************************************************************************
 * 
 * Ce fichier contient toutes les constantes nécessaires au fonctionnement du jeu.
 * En particulier les listes de mots et de phrases proposés à l'utilisateur
 * 
 *********************************************************************************/


const listeMots = [
"astrophysique",
"exoplanète",
"téléportation",
"cyborg",
"intelligence ",
"artificielle",
"univers" ,
"parallèle",
"nanotechnologie",
"transhumanisme",
"colonisation" ,
"spatiale",
"voyage" ,
"temporel",
"extraterrestre",
"génétique",
"clonage",
"manipulation" ,
"génétique",
"androïde",
"mutation",
"matière",
"infini",
"réalité" ,
"virtuel",
"antimatière",
"singularité",
"terraformation",
"fusion",
"nucléaire",
"rayon" ,
"laser",
"bouclier" ,
"énergétique",
"gravité" ,
"artificielle",
"biopunk",
"steampunk",
"dystopie",
"utopie",
"télékinésie",
"réplicateur",
"générateur",
"transfert",
"conscience",
"cyberespace",
"réalité",
"géostationnaire",
"énergie"]


const listePhrases = [
"Destination ténèbres", 
"Mars la Rouge", 
"La Planète des singes", 
"La nuit des temps", 
"Demain les chiens", 
"La cinquième tête de Cerbère", 
"Le cycle d'Hypérion", 
"Rencontres du troisième type",
"Chroniques martiennes", 
"Cristal qui songe", 
"La guerre éternelle", 
"Des fleurs pour Algernon",
"Des milliards de tapis de cheveux", 
"La Zone du dehors", 
"Les Monades urbaines",
"Le problème à trois corps", 
"Le Monde du fleuve", 
"2001 L'Odyssée de l'espace",
"Le meilleur des mondes",
"Le Guide du voyageur galactique",
"La Stratégie Ender",
"Le Cycle de Dune",
"L'homme qui mit fin à l'histoire"
]
